<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Twilio\Rest\Client;

define('ACCOUNT_SID', config('app.twilio')['TWILIO_ACCOUNT_SID']);
define('AUTH_TOKEN', config('app.twilio')['TWILIO_AUTH_TOKEN']);
define('SERVICE_ID', config('app.twilio')['TWILIO_SERVICE_SID']);
class VerificationController extends Controller
{
    protected function client()
    {
        return new Client(ACCOUNT_SID, AUTH_TOKEN);
    }

    public function sendSms(Request $request)
    {

        /**
         * Send SMS Verification Code
         *
         * The verification code will auto generated by twilio
         * You can get the service id on https: //www.twilio.com/console/verify/services
         *
         * https: //www.twilio.com/docs/verify/api-beta/verification-check-beta
         * API Reference -> Verifications
         *
         */
        $sms = $this->client()
            ->verify
            ->v2
            ->services(SERVICE_ID)
            ->verifications
            ->create($request->phone, "sms");

        dd($sms);
    }

    public function checkVerification(Request $request)
    {
        /**
         * Check Status of Verification Code
         *
         * https: //www.twilio.com/docs/verify/api-beta/verification-check-beta
         * API Reference -> Verification Check
         *
         */

        $check = $this->client()
            ->verify->v2->services(SERVICE_ID)
            ->verificationChecks
            ->create($request->code, // code
                array("to" => $request->phone)
            );

        dd($check->status);
    }
}
